### ISSUE TITLE
如果css 图片路径加了query会导致出错

### ISSUE THREAD

**Issue by sudosiyang** [cssdream/cssgrace#15]
如果css这么写
```css
.test{
    background: url(../images/font/blue.png?__sprite) no-repeat;
}
```
会导致如下错误
```
no such file or directory 'xxx/application/views/statics/images/font/blue.png?__sprite'
```

ps:该query为构建工具合并为雪碧图之用

我做了如下修改

```js
//获取css文件中的资源的绝对地址
function getAbsolutePath(sourcePath) {
  return path.resolve(currentFilePath, sourcePath.split("?")[0]);
}
```
可行。。
@yisibl 不知这是BUG，还是我需要哪些配置可以避免？
