### ISSUE TITLE
image-width/height 写在background 前面无法获取正确的图片尺寸

### ISSUE THREAD

**Issue by yisibl** [cssdream/cssgrace#16]
```css
.foo {
  width: image-width;
  height: image-height;
  background: -webkit-image-set(
                    url(../img/line.png) 1x,
                    url(../img/line@2x.png) 2x) 50% 50% no-repeat;
}
```
