### ISSUE TITLE
Add text-indent: 100% mixin

### ISSUE THREAD

**Issue by yisibl** [cssdream/cssgrace#17]
input: 

```css
.foo {
  text-indent: 100%;
}
```

output:

```css
.foo {
  text-indent: 100%;
  overflow: hidden;
  white-space: nowrap;
  word-wrap: normal;
}
``
