### ISSUE TITLE
大部分浏览器不支持 animation-play-state 属性在 animation 属性中缩写

### ISSUE THREAD

**Issue by yisibl** [cssdream/cssgrace#19]
input:

```css
.foo {
  animation: foo 1s 2s infinite linear alternate both paused;
}
```

Will out:

```css
.foo {
  animation: foo 1s 2s infinite linear alternate both;
  animation-play-state: paused;
}
```
