### ISSUE TITLE
增加 clip fallback

### ISSUE THREAD

**Issue by yisibl** [cssdream/cssgrace#22]
input:

```css
.foo {
    clip: rect(5px, 40px, 45px, 5px);
}
```

```css
.foo {
    clip: rect(5px, 40px, 45px, 5px);
    *clip: rect(5px 40px 45px 5px);
}
```
