### ISSUE TITLE
HTTP urls break build

### ISSUE THREAD

**Issue by jsalonen** [cssdream/cssgrace#26]
Use the following test.css to reproduce:

    .foo {
	  background-image: url("http://www.example.com/image.png");
    }

**Comment by yisibl** [comment]
There is no support. 
Next version fixed.

**Comment by jsalonen** [comment]
Hi!

Thank you for your quick response.

I don't need cssgrace to resolve background images over HTTP. I just need that the build won't break if I have these urls in my stylesheet.

**Comment by zenbrent** [comment]
Hi! How is work on the next version going? I just started a fork to do 2 things:

1. to split out each rule into its own .js file, instead of keeping them all in one index.js file
2. to make cssgrace configurable.

I need to disable the image handling in my own project. When I'm done, would you like me to submit a pull request, or are you already working on this?

**Comment by zenbrent** [comment]
I split all the tasks out in my fork at https://github.com/zenbrent/cssgrace

I also made it so it doesn't process images that aren't referenced with image-width or image-height, so if I'm using an image that is served at a different path than it is on my hard drive, there isn't an error. (e.g. I reference url(/images/logo.png), but that's obv. not how it's set up on my computer.)
I haven't made it configurable yet, I may do that in the future.

I agree with #10 that some of these features would be best served as a separate project. For my job, I don't want cssgrace to handle my images, but I do want it to make my css work with older browsers! For my personal projects I would love the image handling, but I don't care about very old browsers.

As always, thank you for all your work. This is a very useful and well-done project. :)

**Comment by yisibl** [comment]
@zenbrent 

Yeah, the next version  I will "to split out each rule into its own .js file" and add browser configuration

Maybe like this:

input:

```css
@browser ie>=8;

.foo {
  display: inline-block;
}
```

output:

```css
.foo {
  display: inline-block;
}
```


input:

```css
@browser ie>=6;

.foo {
  display: inline-block;
}
```

output:

```css
.foo {
  display: inline-block;
  *display: inline;
  *zoom: 1;
}
```
