### ISSUE TITLE
ieOpacityHack not working with `postcss-nested`

### ISSUE THREAD

**Issue by Semigradsky** [cssdream/cssgrace#29]
Input:
```css
td.options {
  text-align: center;

  .link {
    opacity: 0;
  }
}
```

Error:
> ERROR in ./~/css-loader!./~/postcss-loader!./src/scripts/components/users/users.css
Module build failed: TypeError: Cannot read property 'replace' of undefined
    at ieOpacityHack (D:\Dev\git\React\react-admin-example\node_modules\cssgrace\lib\index.js:270:31)
    at D:\Dev\git\React\react-admin-example\node_modules\cssgrace\lib\index.js:472:5
