### ISSUE TITLE
多余的hack

### ISSUE THREAD

**Issue by gucong3000** [cssdream/cssgrace#43]
```CSS
audio, canvas, progress, video {
  display: inline-block;
  *display: inline;
  *zoom: 1;
}
```

这样的CSS代码，会输出为
```CSS
audio, canvas, progress, video {
  display: inline-block;
  *display: inline;
  *zoom: 1;
  *display: inline;
  *zoom: 1;
}
```

建议在插入hack语句前先检查一下是否已有hack
